codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto 
        threshold: 0.5% 
    patch:
      default:
        target: 80% 
        threshold: 1%

comment:
  layout: "diff, files, tree"
  behavior: default
  require_changes: yes

ignore:
  - "tests/*"
  - "examples/*"
