# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_batch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data_batch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61ta_batch.proto\x12\x02pb\"p\n\x10\x44\x61taBatchLabeled\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06labels\x18\x02 \x03(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x03 \x01(\x05\x12\x15\n\ris_last_batch\x18\x04 \x01(\x08\x12\x12\n\nsession_id\x18\x05 \x01(\t\"b\n\x12\x44\x61taBatchUnlabeled\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0b\x62\x61tch_index\x18\x02 \x01(\x05\x12\x15\n\ris_last_batch\x18\x03 \x01(\x08\x12\x12\n\nsession_id\x18\x04 \x01(\tB+Z)github.com/data-dispatcher-service/src/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_batch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/data-dispatcher-service/src/pb'
  _globals['_DATABATCHLABELED']._serialized_start=24
  _globals['_DATABATCHLABELED']._serialized_end=136
  _globals['_DATABATCHUNLABELED']._serialized_start=138
  _globals['_DATABATCHUNLABELED']._serialized_end=236
# @@protoc_insertion_point(module_scope)
